volumes:
  grafana:
  prometheus:

x-log-config: &log-config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "20"

networks:
  tor_net:
    ipam:
      driver: default
      config:
        - subnet: "172.31.255.0/24"

services:
  prometheus:
    image: prom/prometheus:${PROM_TAG:-v2.36.0}
    command:
      - --config.file=/etc/prometheus/config.yaml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=${PROM_RETENTION:-360d}
    container_name: wownerod_prometheus
    restart: unless-stopped
    depends_on:
      exporter:
        condition: service_started
    # ports:
    #   - 127.0.0.1:9090:9090
    volumes:
      - prometheus:/prometheus
      - ./files/prometheus/config.yaml:/etc/prometheus/config.yaml:ro
    networks:
      - tor_net
    <<: *log-config
  grafana:
    user: "1000"
    command:
      - -config=/etc/grafana/grafana.ini
    container_name: wownerod_grafana
    restart: unless-stopped
    image: grafana/grafana:${GRAFANA_TAG:-10.1.4}
    ports:
      - 127.0.0.1:${GRAF_PORT:-3000}:3000
    volumes:
      - grafana:/var/lib/grafana
      - ./files/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./files/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./files/grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      HOSTNAME: grafana
      GF_SERVER_ROOT_URL: ${GRAFANA_URL}
      GF_ANALYTICS_REPORTING_ENABLED: "false"
      GF_ANALYTICS_CHECK_FOR_UPDATES: "false"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_LOG_LEVEL: "debug"
      GF_AUTH_ANONYMOUS_ENABLED: "${GF_AUTH_ANONYMOUS_ENABLED:-true}"
      GF_AUTH_BASIC_ENABLED: "${GF_AUTH_BASIC_ENABLED:-false}"
      GF_AUTH_DISABLE_LOGIN_FORM: "${GF_AUTH_DISABLE_LOGIN_FORM:-true}"
      GF_SECURITY_ADMIN_PASSWORD: "${GF_SECURITY_ADMIN_PASSWORD}"
      GF_SECURITY_ADMIN_USER: "${GF_SECURITY_ADMIN_USER}"
    networks:
      - tor_net
    <<: *log-config
  exporter:
    container_name: wownerod_exporter
    build:
      context: .
      dockerfile: dockerfiles/exporter
    restart: unless-stopped
    depends_on:
      wownerod:
        condition: service_started
    # ports:
    #   - 127.0.0.1:9000:9000
    command:
      - --wownero-addr=http://wownerod:${UNRESTRICTED_PORT:-34570}
    networks:
      - tor_net
    <<: *log-config
  nodemapper:
    container_name: wownerod_nodemapper
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfiles/nodemapper
    depends_on:
      wownerod:
        condition: service_started
    environment:
      NODE_HOST: wownerod
      NODE_PORT: 34570
    # ports:
    #   - 127.0.0.1:${MAPPER_PORT:-5000}:5000
    networks:
      - tor_net
    <<: *log-config
  tor:
    container_name: wownerod_tor
    build:
      context: .
      dockerfile: dockerfiles/tor
    restart: unless-stopped
    # ports:
      # - 127.0.0.1:9050:9050
    networks:
      tor_net:
        ipv4_address: 172.31.255.250
    <<: *log-config
  i2p:
    container_name: wownerod_i2p
    build:
      context: .
      dockerfile: dockerfiles/i2p
    restart: unless-stopped
    # ports:
        # - 127.0.0.1:4444:4444
    networks:
      tor_net:
        ipv4_address: 172.31.255.251
    <<: *log-config
  wownerod:
    container_name: wownerod
    build:
      context: .
      dockerfile: dockerfiles/wownero_compile
      args:
        THREADS: ${THREADS:-2}
    restart: unless-stopped
    depends_on:
      tor:
        condition: service_started
      i2p:
        condition: service_started
    volumes:
      - ${DATA_DIR:-./data}:/data
    ports:
      - ${P2P_PORT:-34567}:34567                    # p2p
      - ${RESTRICTED_PORT:-34568}:34568             # restricted rpc
      - 127.0.0.1:${ZMQ_PORT:-34569}:34569          # zmq
      - 127.0.0.1:${UNRESTRICTED_PORT:-34570}:34570 # unrestricted rpc
    command:
      - wownerod
      - --data-dir=/data
      - --p2p-bind-ip=0.0.0.0
      - --p2p-bind-port=34567
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=34568
      - --zmq-rpc-bind-ip=0.0.0.0
      - --zmq-rpc-bind-port=34569
      - --rpc-bind-ip=0.0.0.0
      - --rpc-bind-port=34570
      - --non-interactive
      - --confirm-external-bind
      - --public-node
      - --log-level=0
      - --rpc-ssl=disabled
      - --ban-list=/ban_list.txt
      - --tx-proxy=tor,172.31.255.250:9050,disable_noise,24
      - --tx-proxy=i2p,172.31.255.251:4447,disable_noise,24
    networks:
      - tor_net
    <<: *log-config
